version: "3.9"

services:
  social-api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: social-api
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://social:social@postgres:5432/social?connection_limit=20&pool_timeout=30
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: social-db
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: social
      POSTGRES_DB: social
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: social-redis
    ports:
      - "6380:6379"

  pg-adminer:
    image: adminer:latest
    container_name: social-adminer
    ports:
      - "1080:8080"
    environment:
      # Optional: Prefills the 'Server' field in the login screen
      ADMINER_DEFAULT_SERVER: postgres 
    depends_on:
      - postgres

volumes:
  pgdata:
